### ISSUE TITLE
Stylesheet doesn't work inside table headers

### ISSUE THREAD

**Issue by alemedeiros** [yogthos/clj-pdf#100]
Given the following example:
```clj
(pdf
    [{:stylesheet {:my-header {:style :bold :size 16}}}
     [:chunk "Hello World"]
     [:table 
      {:header [[:chunk "Table header"]]}
      [[:cell [:chunk "Element 1"]]]
      [[:cell [:chunk "Element 2"]]]
      ]
     ]
    "sample.pdf")
```

I can generate a pdf just fine, but appending `.my-header` to the header chunk gives me a `failed to parse` Exception. Any other chunk works fine with the stylesheet.

**Comment by yogthos** [comment]
Yeah that looks like an omission in how styling is applied. I won't have time to take a look in the near future unfortunately. If you get a chance to look, I would be glad to help with a pr though.

**Comment by jwr** [comment]
I just got bitten by this problem (table headers not inheriting the global font configuration). Thanks for working on this! I'm hoping a release with the fix is coming soon.

**Comment by alemedeiros** [comment]
I'm almost done with the fix, I just wanted and ok (or suggestions) from @yogthos.

But I'm really glad that my changes may help someone else :)

**Comment by yogthos** [comment]
@alemedeiros if you think you're happy with the fix, I could merge it in. Unfortunately, I'm a bit swamped, so don't have time to dig into this myself. I took a cursory look, and the change seems to make sense.

@jwr could you try the branch and see if the change works for you, I could push out a release if you guys are happy with it.

**Comment by alemedeiros** [comment]
Sorry for taking too long to answer. For me it's good to go. I couldn't take a throughout look on the tests, but I tried a lot of examples. when I get some free time I want to take a look on it (and maybe on how to solve another issue).

**Comment by yogthos** [comment]
Ok cool, I'll try take a look at the tests sometime this week, and merge it in if everything looks good. :)

**Comment by jwr** [comment]
I'm happy to confirm that `2.2.10` fixes the problem for me. Thanks!

**Comment by yogthos** [comment]
:+1:
