### ISSUE TITLE
Completely remove footer

### ISSUE THREAD

**Issue by julianwegkamp** [yogthos/clj-pdf#108]
Hi,

Is there currently a way to completely remove the footer? When I add :footer false to the document metadata the footer and the page number are still rendered (page number on the left instead of on the right).

Thanks,
Julian

**Comment by yogthos** [comment]
You can get rid of page numbers in the footer as follows:

```clojure
[{:footer {:page-numbers false}}
 ...]
```

**Comment by julianwegkamp** [comment]
Thanks but I'm afraid this does not solve my problem. There is still (a lot of) space reserved for the (empty) footer. Is there a way to completely remove the footer or set the height to 0?

**Comment by yogthos** [comment]
You could try changing the margins for the document to see if that will help. The footer element shouldn't be added at all with the above setup.

**Comment by julianwegkamp** [comment]
An example with enough text to fill a couple of pages. When I set the bottom-margin to 0 there is still room reserved for the footer. I found a workaround. When I set a negative bottom-margin the footer disappears. :bottom-margin -40 seems to do the trick.

```clojure
(require '[clj-pdf.core :as pdf])
(defn example-pdf [path bottom-margin]
  (pdf/pdf
    [{:size [200 150]
      :left-margin 0
      :right-margin 0
      :top-margin 0
      :bottom-margin bottom-margin
      :footer {:page-numbers false}}
     [:paragraph "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel ultrices urna, non fringilla enim. Cras ipsum lorem, cursus interdum enim sed, porttitor vestibulum orci. Morbi consequat dui lorem, ac pretium erat congue ac. Nullam eget molestie nibh, in finibus mi. Fusce laoreet, augue sit amet vehicula congue, sem arcu venenatis magna, non ornare lectus neque nec felis. Etiam eget magna porttitor, congue turpis quis, imperdiet ante. Fusce non tortor eu est pretium bibendum. Aenean ac nisi nibh. Morbi bibendum felis non varius efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras pulvinar non mi at pharetra. Sed semper tincidunt malesuada. In aliquet purus nisl, vel condimentum ex bibendum eu."]]
    path))

(example-pdf "/tmp/with-footer.pdf" 0)
(example-pdf "/tmp/without-footer.pdf" -40)
```

**Comment by yogthos** [comment]
Would have to look what's happening there. The margin is set explicitly [here](https://github.com/yogthos/clj-pdf/blob/19b1d820a3fc7ccca95a13aa1fdb480c451c0323/src/clj/clj_pdf/core.clj#L972), and the footer is added [here](https://github.com/yogthos/clj-pdf/blob/19b1d820a3fc7ccca95a13aa1fdb480c451c0323/src/clj/clj_pdf/core.clj#L959). I've improved [this check](https://github.com/yogthos/clj-pdf/blob/19b1d820a3fc7ccca95a13aa1fdb480c451c0323/src/clj/clj_pdf/core.clj#L923). However, the footer should not be set when using `:footer {:page-numbers false}` currently.

If you have a chance to take a look at this, a pr is welcome.

**Comment by julianwegkamp** [comment]
Commit 7b4cd0c4ae884ce66440cf3df3c669c17a1e931e fixed my problem with the footer when I use `:footer false`. I'd say this is correct behaviour.

You mention that when using `:footer {:page-numbers false}` the footer shouldn't be set. I suppose  because there is no content for the footer the footer should 'collapse'? I can probably take a better look this weekend...

**Comment by yogthos** [comment]
Great, and I was wrong about that bit. Since the check is `(or footer page-numbers?)`, the page numbers wouldn't be set, but the footer would be a map, so it would still be added. The fix ensures that page numbers are treated as false when the footer is set to false.

**Comment by julianwegkamp** [comment]
Thanks @yogthos. After some thought: do you agree that since `:footer {:page-numbers false}` explicitly references :footer and its value is not false it should result in an empty footer and not in the complete removal?

**Comment by yogthos** [comment]
I think that should result in an empty footer since footer has a value.

**Comment by julianwegkamp** [comment]
OK, then we'll leave it as it is. Thanks for your time and effort

**Comment by yogthos** [comment]
No problem, and I pushed out a new version with the fix and this pr https://github.com/yogthos/clj-pdf/pull/109
