### ISSUE TITLE
Add :color meta for :line section

### ISSUE THREAD

**Issue by dcavoulacos** [yogthos/clj-pdf#118]
iText's LineSeparator (and DottedLineSeparator) accepts a color param, but the :line section fronting those separators does not. Please add!

**Comment by dcavoulacos** [comment]
Using your `font` method as an example, would this work?

```
(defn- line [{dotted? :dotted, gap :gap, [r g b] :color} & _]
  (let [^LineSeparator lineSeparator (if dotted?
                                       (if gap
                                         (doto (new DottedLineSeparator) (.setGap (float gap)))
                                         (new DottedLineSeparator))
                                       (new LineSeparator))]
    (doto lineSeparator (if (and r g b) (.setLineColor (new Color r g b))) 
                        (.setOffset -5))))

**Comment by yogthos** [comment]
That looks like it should work, if you want to try it locally I can add it in or if you'd like to make a pr then I can push out a new version.

**Comment by yugensoft** [comment]
Was this issue closed by https://github.com/yogthos/clj-pdf/pull/119 ?

**Comment by yogthos** [comment]
yup, closing :)
