### ISSUE TITLE
How to set font for header?

### ISSUE THREAD

**Issue by skuteli** [yogthos/clj-pdf#120]
Hi, thanks for an awesome lib.
I'm trying to generate pdf with unicode characters in header;
Is there a way to specify custom font for header element? :font seems to affect only the body of the document.

**Comment by yogthos** [comment]
I think that might be an omission in how the document is being initialized currently. The header/footer logic lives [here](https://github.com/yogthos/clj-pdf/blob/c617b9b68cb2a72096bbf25dd8b101cb38de5056/src/clj/clj_pdf/core.clj#L945), and it might just be a matter of passing the font to the function that generates the header element. I probably won't have time to look in the immediate future, but if you're up for doing a pr I can definitely help with that.

**Comment by skuteli** [comment]
Now I realized I've been using 2.2.8. It works ok in 2.2.17
Sorry for wasting your time.

**Comment by yogthos** [comment]
good news, and glad the library is helpful :)
