### ISSUE TITLE
Correct syntax for multi-level list

### ISSUE THREAD

**Issue by EmergentBehavior** [yogthos/clj-pdf#127]
What is the correct syntax for generating a list with multiple levels?

E.g.

- Level 1
  - Level 2
  - Level 2
- Level 1

I've tried with nested `[:list ...]` but get an error `No matching ctor found for class cljpdf.text.ListItem`.

Thanks!

**Comment by yogthos** [comment]
You just have to wrap the inner list using a `:phrase` tag:

```clojure
[:list
       "foo"
       [:phrase [:list "foo" "bar"]]]
```

**Comment by EmergentBehavior** [comment]
Thanks for quick response!

**Comment by yogthos** [comment]
No prob, sounds like we can close this? :)

**Comment by EmergentBehavior** [comment]
Yes :) though might be good to add to docs/Readme.md in future

**Comment by yogthos** [comment]
good call, just added the example 👍
