### ISSUE TITLE
narrow paragraph

### ISSUE THREAD

**Issue by chrismurrph** [yogthos/clj-pdf#129]
Is there a way to have a paragraph that is narrower than the others? `:indent` works fine for the left - but I would like the same indent to be applied to the right. I am going to need to implement this, perhaps by inserting the line breaks myself. Can you recommend an approach? Once done (even as a hacky workaround), I'll be able to refer to it from this issue, as what I'm doing is all open source: https://github.com/chrismurrph/mail-merge/tree/master

**Comment by yogthos** [comment]
There's no direct way to do that at the moment. As a work around you could stick it in a table and pad it using an empty cell. I'll take a look to add this in.

**Comment by chrismurrph** [comment]
The thing that I'm doing at the moment is to provide all the separate lines, each one a string, and then make chunks out of them with a "\n" on the end. The downside I see to this approach is that justified alignment no longer works. If the indent were to be for both left and right 'margins', then you would expect justified alignment to work, because it does with only the left indent. I suspect this issue is also an issue with the underlying iText library.

**Comment by chrismurrph** [comment]
Here is my workaround: https://github.com/chrismurrph/mail-merge/blob/master/src/common/common.clj#L106

**Comment by yogthos** [comment]
And just pushed out a new version with a few new options:

```
* :indent-left       number (indentation for the paragraph on the left)
* :indent-right      number (indentation for the paragraph on the right)
* :spacing-before    number
* :spacing-after     number
```

let me know if this makes things easier

**Comment by chrismurrph** [comment]
Thanks that works very well (does alignment justification). From my experience this enhancement will be a big help to the library. I tested all those keywords except `:spacing-before`. Thanks again.

**Comment by yogthos** [comment]
👍
