### ISSUE TITLE
[Q] Can I combine fixed and percentage widths?

### ISSUE THREAD

**Issue by yatesco** [yogthos/clj-pdf#136]
Hi,

Is it possible to specify both fixed and percentage based widths _at the same time_. For example, I know the width of some columns will never change and I want to specify other columns as a percentage of the remaining space.

For example, given the following columns:
["ID" "Name" "Notes" "Preferred?"]

I know how many pixels "ID" and "Preferred?" will be. I would then ideally like to state that "Name" should take up no more than 20% (preferably less) before wrapping/cutting off and "Notes" should take up 80%. The 20 and 80% refer to the total amount of space - the fixed widths.

At the moment it seems I can either provide fixed widths for all, or percentage based widths for all, but I can provide a mix, nor can I specify max-widths.

Is that possible, or is this venturing into far more complex layout-based engines (aka browsers)?

**Comment by yogthos** [comment]
It's not possible at the moment, but the underlying iText API might support this. I have haven't dug into it as I haven't needed this yet. Another option might be to use nested tables. You could have a top level table that has fixed with, and then an inner one with percentage width.

**Comment by yatesco** [comment]
OK, thanks @yogthos - closing for now.
