### ISSUE TITLE
[Q] Composite components in the footer

### ISSUE THREAD

**Issue by yatesco** [yogthos/clj-pdf#137]
Hi,

The documentation states that the footer must be a string. Is there a way to have multiple segments in the footer instead of a simple string?

For example, branding image on the left, Copyright in the middle and page numbers on the right.

Is this possible?

Thanks!

**Comment by yogthos** [comment]
The `:footer` can also take a table, e.g:

```clojure
:footer {:table
          [:pdf-table
           {:border false}
           [20 15 60]
           ["This is a table footer" "second column" "third column"]]
```

You should be able to get the formatting you need that way. This is described after the configuration section, I'll update the docs to make it more clear.

**Comment by yatesco** [comment]
Thanks @yogthos

**Comment by yatesco** [comment]
Hmm, the only reservation is that there doesn't seem to be a way to access currentPageNumber/totalPages variables. If you use the above table _and_ set `:page-numbers` then the table is stacked above the page numbers.

Any suggestions?

**Comment by yogthos** [comment]
Unfortunately, that's a limitation of the way the original page numbering logic is implemented. Perhaps, it could be possible to check when the table footer is used in conjunction with the page count, and position them on the same line.
