### ISSUE TITLE
`:under true` has no effect for the watermark

### ISSUE THREAD

**Issue by yatesco** [yogthos/clj-pdf#138]
Hi,

Given:
``` clojure
       :watermark  {
                                :render draw-watermark
                                :under true
                                }
```
I would expect the image to be under the other elements but it isn't, it is on top.

If I use that `fn` elsewhere with a normal `[:graphics....}` then it works as expected. Is `under` not supported for watermarks?

Thanks!

**Comment by yogthos** [comment]
The watermark sets `:under true` in its default renderer [here](https://github.com/yogthos/clj-pdf/blob/e5fbfb25537776c21b47af14f3b55ddca449503e/src/clj/clj_pdf/core.clj#L985). So, it should always be set to that in theory.

**Comment by yatesco** [comment]
It definitely isn't working for me. Later today when work settles down I will prepare a demo repo, if that would help.

**Comment by yogthos** [comment]
I just tried locally, and this appears to work as expected:

```clojure
(pdf
  [{:watermark
    {:render (fn [g2d]
               (.setColor g2d Color/GREEN)
               (.drawString g2d "DRAFT COPY" 0 0))
     :translate [10 10]
     :rotate 45
     :scale 8}}
   [:paragraph "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]]
  "test.pdf")
```

The watermark appears below the paragraph.

**Comment by yatesco** [comment]
It appeared under the text but not under table/cell borders

**Comment by yogthos** [comment]
Ah I see, it should work as expected with the pdf-table.

**Comment by yatesco** [comment]
Ah OK, I will try the pdf-table. I was using a "plain" table. Are pdf-table's generally preferable?

**Comment by yogthos** [comment]
Yeah, pdf-table is the newer implementation, and it should do everything the original table does. I actually created [this issue](https://github.com/yogthos/clj-pdf/issues/139) for an enhancement to replace the current table with the pdf-table internally. Hope to get around to that at some point soon. :)

**Comment by yatesco** [comment]
Ok. Hands for the info, no need to keep this around then. Thanks again.
