### ISSUE TITLE
Unable to hide page number in footer when footer table is specified

### ISSUE THREAD

**Issue by priornix** [yogthos/clj-pdf#142]
Thanks @yogthos for this great library! 

There is an issue that I noticed. For the footer portion, when `:table` is specified, the page number cannot be hidden. In the following code, the page number is not hidden:

Eg:
```clojure
{:footer {:table [:pdf-table {} nil [""]] :page-numbers false}}
```

When `:table` is not specified, the page number will be hidden

Version used: `2.2.28`

**Comment by yogthos** [comment]
Yeah that looks like a bug, I'll try make some time to look at this.

**Comment by yogthos** [comment]
Should be fixed in `2.2.29`, let me know if this works for you.

**Comment by priornix** [comment]
Excellent work! It's working now! 👍

**Comment by yogthos** [comment]
👍
