### ISSUE TITLE
dependency on [org.swinglabs/pdf-renderer "1.0.5"] is it still needed?

### ISSUE THREAD

**Issue by Voooza** [yogthos/clj-pdf#144]
I noticed a dependency on [org.swinglabs/pdf-renderer "1.0.5"] in project.clj. I wonder if it is really needed because I haven't found any references to it.

**Comment by yogthos** [comment]
It's been a while since it got added, I can't see why it's needed off top of my head. I'll do some testing without it to see if it's used indirectly somewhere. I'll push out a release without it if everything works.

**Comment by yogthos** [comment]
It's been a while since it got added, I can't see why it's needed off top of my head. I'll do some testing without it to see if it's used indirectly somewhere. I'll push out a release without it if everything works.

**Comment by yogthos** [comment]
Did some testing, and it doesn't look like the dependency is needed. I pushed out `2.2.30` with it removed. Thanks for noting this.
