### ISSUE TITLE
Turkish characters don't work

### ISSUE THREAD

**Issue by ertugrulcetin** [yogthos/clj-pdf#146]
I've noticed that some Turkish characters don't appear in pdf when I use this nice library. Here are the chars: lower case version: `şğı`  upper case version: `ŞĞİ`

**Comment by yogthos** [comment]
Have you tried using a [custom font](https://github.com/yogthos/clj-pdf#using-custom-ttf-fonts) ?

**Comment by ertugrulcetin** [comment]
yep it worked thanks!

**Comment by yogthos** [comment]
👍
