### ISSUE TITLE
Add possibility to insert table into footer

### ISSUE THREAD

**Issue by paologf** [yogthos/clj-pdf#19]
I forked project and added the possibility to insert a table into the pdf header (pool-request soon). I'm trying also to add a table into the footer but the method i used for the header is not working. The steps are : create a paragraph ("container"), add stuff to the "container" such a table, pass this "container" as argument of the HeaderFooter constructor and set Header/Footer to the document.
Any ideas or suggestion?
Thanks in advance.

**Comment by yogthos** [comment]
implemented with this commit https://github.com/yogthos/clj-pdf/commit/22c7ee75c17254032bb3c6edecf47ed7014844a5

**Comment by yogthos** [comment]
the footer can now contain a :table key that looks as follows:

```clojure
{:footer
              {:table
                             [:pdf-table
                              {:bounding-box     [50 100]
                               :horizontal-align :right
                               :spacing-before   100
                               :width            500}
                              [10 20 15]
                              ["foo" [:chunk {:style :bold} "bar"] [:phrase "baz"]]
                              [[:pdf-cell "foo"] [:pdf-cell "foo"] [:pdf-cell "foo"]]
                              [[:pdf-cell "foo"] [:pdf-cell "foo"] [:pdf-cell "foo"]]]
               :page-numbers true}}
```
