### ISSUE TITLE
Error: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by adamneilson** [yogthos/clj-pdf#42]
I have an error when trying to run a standalone jar when `[clj-pdf "1.11.26"]` is in the dependencies list. My project is an API built using Liberator that generates a PDF invoice after a trade and sends this as an attachment via email to the customer. 

Developing this locally on OSX I use `lein uberjar` to build the project and then using the following command: `$ java -javaagent:/usr/local/myproject/newrelic.jar -jar target/myproject-0.8.16-standalone.jar &` it runs without any issues.

If I then take that exact same jar file over to the production environment (Ubuntu 12.04) and try to run it I get the following error:
```
$ java -javaagent:/usr/local/myproject/newrelic.jar -jar target/myproject-0.8.16-standalone.jar &
$ Error: Invalid or corrupt jarfile target/myproject-0.8.16-standalone.jar
```

I also tried creating the jar on the server and it compiles and packages itself correctly but again complains about an invalid jar when I try to run it.

When I remove the clj-pdf (and the pdf generator function) the project builds and runs without issue.

Java version is the following:

```
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

This suggests the problem is with the JVM so I did a bit of searching around the interwebs for a clue as to what might be causing this.

First off I tried swapping the order of the dependencies as mentioned as a solution in a similar error [here](http://stackoverflow.com/questions/13021423/invalid-or-corrupt-jar-file-built-by-maven-shade-plugin). This didn't help.

I then found [this blog post](http://dan.bodar.com/2014/02/17/error-invalid-or-corrupt-jarfile/) which suggested starting the service this way: 

```
java -javaagent:/usr/local/myproject/newrelic.jar -cp target/myproject-0.8.16-standalone.jar myproject.core
```

This worked. But I don't really understand why.

Before I go and update all my deployment scripts to the alternative command I was wondering if this was a known issue?

**Comment by yogthos** [comment]
I haven't seen this happen myself, and I can't reproduce the issue either. I've built a runnable uberjar on OS X and was able to run it on Ubuntu just fine. However, I'm using JDK/JRE 8 on both.

**Comment by adamneilson** [comment]
Ok thanks, I think the path of least resistance for me is to change the execution command. Once I get around to upgrading to JRE8 I'll give it another shot.

Thanks again.

**Comment by yogthos** [comment]
definitely let me know if you find out what's causing it specifically

**Comment by amoe** [comment]
I'd speculate that this was probably down to this bug in Java 7, and not due to clj-pdf: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7191282

**Comment by adamneilson** [comment]
Ah thanks @amoe, that definitely looks like the cause and also explains why @yogthos was unable to reproduce. I love a happy ending ;-)
