### ISSUE TITLE
The cell-border metadata of pdf-table is broken after version 1.11.25

### ISSUE THREAD

**Issue by lmanolov** [yogthos/clj-pdf#47]
The cell-border metadata of pdf-table is broken after version 1.11.25. Here is a sample test:
```
[:pdf-table
     [100]
     [[:pdf-cell {:set-border [:bottom]}
       [:pdf-table
        {:cell-border true}
        [50 50]
        ["A" "B"]]]]]
```
The result in 1.11.25 is:
![result 1 11 25](https://cloud.githubusercontent.com/assets/23609/7300176/55ba1d60-e9e3-11e4-8d0e-b22b29b5ff5c.png)

The result in 1.11.26 (and 2.0.3) is:
![result 1 11 26](https://cloud.githubusercontent.com/assets/23609/7300187/6b01eaea-e9e3-11e4-8ff0-af800af3d8ce.png)

It seems that in version 1.11.26 (and later) the inner pdf-table inherits `{:set-border [:bottom]}` from the enclosing pdf-cell but does not respect the `{:cell-border true}` metadata. I believe that this problem was introduced in this commit (most probably in the refactoring of pdf-cell): https://github.com/yogthos/clj-pdf/commit/ae92eb677cfb6014c2c143a57773b59247f8299e?diff=split

**Comment by yogthos** [comment]
Yeah that looks like the issue, I might not have time to look at a fix this week. Would you be up for doing a pr with a fix?

**Comment by yogthos** [comment]
looking at it a little bit here, it looks like `:set-border` overrides the `:cell-border`, so as a workaround you can explicitly disable it in the inner table:

```clojure
[:pdf-table
       [100]
       [[:pdf-cell {:set-border [:bottom]}
         [:pdf-table
          {:cell-border true
           :set-border nil}
          [50 50]
          [[:pdf-cell "A"] "B"]]]]]
```

**Comment by yogthos** [comment]
Thinking about it a bit more, this is really a question of what properties should take precedence. Should `:border` override `:set-border` or vice versa. I'm tempted to say that the new behavior is actually correct.

**Comment by lmanolov** [comment]
Thank you for the `:set-border nil` tip! It has solved the problem in my case. I am OK to close the issue.

**Comment by yogthos** [comment]
sounds good
