### ISSUE TITLE
Table header :background-color does not work

### ISSUE THREAD

**Issue by ozjongwon** [yogthos/clj-pdf#49]
I've tried with existing example like:

[:table {:header [{:background-color [100 100 100]}
                  [:paragraph {:style :bold :size 15} "Foo"]
                  [:paragraph {:align :center :style :bold :size 15} "Bar"]]}
  ["foo" "bar"]]

Thanks

**Comment by yogthos** [comment]
Ah this was a typo, currently the header expects a `:color` key. I've just pushed out a new version that changes it to `:background-color` for consistency.

**Comment by nukecoder** [comment]
It's actually ```:backdrop-color ``` now.
