### ISSUE TITLE
Ensuring an even number of pages?

### ISSUE THREAD

**Issue by kryft** [yogthos/clj-pdf#51]
Is there an easy way to ensure that the output from `pdf` has an even number of pages? A crude approach would be to write it to a file and then use something like [pdfboxing](https://github.com/dotemacs/pdfboxing) to check the number of pages, and then recreate the document with an extra blank page if that number is odd, but a more elegant solution would be nice. :)

(I'm using clj-pdf to generate a printable PDF out of a bunch of documents of varying lengths. One should be able to separate the documents after printing the PDF double-sided, so each individual document should have an even number of pages.)

**Comment by yogthos** [comment]
There isn't a way to do it at the moment, although it should be possible to do in principle as the underlying iText lib allows post processing of docs. I uses that in the [write-total-pages](https://github.com/yogthos/clj-pdf/blob/b0b680cff1e18e5b5a9fadcf8f2c7c0f308d1956/src/clj_pdf/core.clj#L829) function to check the number of pages. Presumably, you would be able to do something similar to insert blank pages as well.

Unfortunately, I won't have time to look at adding a feature for that in the near future. If you'd be up for doing a pr for this I'd be glad to merge it in though.

**Comment by kryft** [comment]
Thanks for the quick response! I'm happy to try to add this myself if you think it makes sense as a feature.

The first approach that comes to mind would be to add an `:ensure-even-number-of-pages` metadata field that would cause `pdf` to insert a blank page at the end if necessary. (I could then in my own application call `pdf` separately for each of my documents using the same output stream.) Does that sound reasonable?

**Comment by yogthos** [comment]
Yeah that sounds great to me, I'm sure this could be useful for others as well. :)
