### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by AshtonKem** [yogthos/clj-pdf#54]
Looks like something changed on Maven, as the com.lowagie package has changed to become com.itextpdf. I now get the following error compiling anything:

Exception in thread "main" java.lang.ClassNotFoundException: com.lowagie.text.pdf.PdfTemplate, compiling:(clj_pdf/graphics_2d.clj:1:1)

**Comment by coyotespike** [comment]
Yes, same here.

**Comment by coyotespike** [comment]
After testing the fix, I've submitted a pull request.

**Comment by yogthos** [comment]
jars publised to maven aren't normally supposed to change, but looks like this is the case here

**Comment by yogthos** [comment]
I pushed a new version that uses the `ibiblio` mirror, if you remove the current maven cache with `rm -rf ~/.m2/repository/com/lowagie` and use version `0.2.7` then everything should work as expected.

**Comment by yogthos** [comment]
looks like iText guys intentionally break the Maven repo for `0.4.x` releases 2 days ago with [this update](https://search.maven.org/#artifactdetails%7Ccom.lowagie%7Citext%7C4.2.2%7Cpom)

**Comment by haraldkoch** [comment]
Yes, it looks like someone not associated with itextpdf.com released version 4.2.x independently. It appears that the itextpdf.com people then took offense, and on July 10th 2015 they published .pom files to Maven Central with the redirects to their new version 5 artifacts. See the timestamps on https://repo1.maven.org/maven2/com/lowagie/itext/ for evidence?

**Comment by yogthos** [comment]
@coyotespike ok pushed out a fork of the latest LGPL iText to Clojars and released a new version of clj-pdf that uses it `2.0.8`, everything should be back to normal

**Comment by coyotespike** [comment]
You're the man, everything's working.
