### ISSUE TITLE
Recompile iText fork against older Java version

### ISSUE THREAD

**Issue by warrensplayer** [yogthos/clj-pdf#56]
@yogthos It appears that when you created the fork of iText to push to clojars to solve #54 , that you compiled it with a target of Java 8.  Any chance you could repush that fork compiled to be compatible with an earlier version of Java?

I am working on a project that has been using your "json-to-pdf" library and so is using this library as a dependency.  This project still using Java 7, so we are now getting a `java.lang.UnsupportedClassVersionError` when trying to use the newest version of your library that uses the iText fork.  It appears that the `com.itextpdf` version of the library in the maven repo is compatible with Java 5.

Thanks so much!

**Comment by yogthos** [comment]
Oh yeah sure thing.

**Comment by warrensplayer** [comment]
Thanks!

**Comment by yogthos** [comment]
could you try with the new dependency and see if it works properly?

```xml
<dependency>
  <groupId>itext</groupId>
  <artifactId>itext</artifactId>
  <version>4.2.1</version>
</dependency>
```

if it looks good, I'll update clj-pdf and json-to-pdf libs

**Comment by warrensplayer** [comment]
It worked!  I will keep an eye on your other projects to see when they are updated.  Thanks again!

**Comment by yogthos** [comment]
ok great, I just pushed out new versions using the `4.2.1` dependency, let me know if it's all working and we can close this :)

**Comment by warrensplayer** [comment]
When you pushed the new version of `json-to-pdf`, you updated its version number but forgot to update the version of `clj-pdf` to `2.0.9`.

**Comment by yogthos** [comment]
oh oops

**Comment by yogthos** [comment]
ok this time for sure :)

**Comment by warrensplayer** [comment]
Looks good now with json-to-pdf version 0.7.5, clj-pdf version 2.0.9 and itext/itext version 4.2.1.

Feel free to close out this issue.

**Comment by yogthos** [comment]
:+1:
