### ISSUE TITLE
Problems creating Unicode (cyrillic) PDF-s

### ISSUE THREAD

**Issue by dejanostojic** [yogthos/clj-pdf#57]
I am having troubles generating Unicode in PDF.
For example this code prints only ASCII:

(pdf
  [{}
   [:paragraph "ASCII works"]
   [:paragraph "prints only arrows: -->Ћирилица<--"]]
  "/path/to/doc.pdf")

I've tried setting {:font {:encoding :unicode}} metadata but am failing to get this working. 
By the way thanks for this great library.
Thanks, 
Dejan.

**Comment by yogthos** [comment]
Looking at the [pr](https://github.com/yogthos/clj-pdf/pull/45/files) for this, it looks like you have to supply a custom font as well.

**Comment by ForNeVeR** [comment]
@yogthos, loading custom fonts is the most confusing for newbies who are trying to work with cyrillic encodings. I think that the documentation could be improved to address that issue. The simplest example that worked for me:

```
(pdf
  [{:font {:encoding :unicode
           :ttf-name "C:\\Windows\\Fonts\\Arialuni.ttf"}}
  [:phrase "тест 123"]]
  "doc.pdf")
```

Maybe some additional examples should be added to address loading fonts from resources etc. This is really poorly documented even in the [upstream docs](http://api.itextpdf.com/itext/com/itextpdf/text/pdf/BaseFont.html), so it'll really help if you document it here.

**Comment by yogthos** [comment]
Yeah that's a great idea, I'll update the docs with an example.
