### ISSUE TITLE
Bouncycastle dependencies and problems with clj-oauth

### ISSUE THREAD

**Issue by kolemannix** [yogthos/clj-pdf#59]
I've seen some issues involving older versions of clj-pdf using old versions of iText that were resolved in version 1.5.0 when yogthos pushed iText 1.4 to clojars and pulled it in as a dependency directly in clj-pdf.

My issue is very similar to this: it seems that when clj-pdf pulls in org.jfree/jfreechart "1.0.15", jfreechart brings in an old version of iText, one which uses the outdated "com.lowagie" prefix. This old version of iText brings in an old version of some BouncyCastle libs that are causing my OAuth code elsewhere in my project to fail.

Here's a sample of the problematic dependency tree:

```
[clj-oauth "1.5.2" :exclusions [[clj-http] [org.apache.httpcomponents/httpclient] [org.apache.httpcomponents/httpcore]]]
   [org.bouncycastle/bcpkix-jdk15on "1.50"]
   [org.bouncycastle/bcprov-jdk15on "1.50"]
 [clj-pdf "2.0.9"]
   [itext "4.2.1"]
     [dom4j "1.6.1"]
     [jfree/jfreechart "1.0.12"]
       [jfree/jcommon "1.0.15"]
     [org.bouncycastle/bctsp-jdk14 "1.38"]
       [org.bouncycastle/bcmail-jdk14 "1.38"]
       [org.bouncycastle/bcprov-jdk14 "1.38"]
     [org.swinglabs/pdf-renderer "1.0.5"]
   [org.apache.xmlgraphics/batik-gvt "1.7"]
     [org.apache.xmlgraphics/batik-awt-util "1.7"]
     [org.apache.xmlgraphics/batik-bridge "1.7"]
       [...]
     [org.apache.xmlgraphics/batik-util "1.7"]
   [org.jfree/jfreechart "1.0.15"]
     [com.lowagie/itext "2.1.5"]
       [bouncycastle/bcmail-jdk14 "138"]
       [bouncycastle/bcprov-jdk14 "138"]
     [org.jfree/jcommon "1.0.17"]
     [xml-apis "1.3.04"]
```

Unfortunately, three different version of bouncycastle/bcprov are being pulled in, one by clj-oauth, and 2 by clj-pdf:
```
[clj-oauth "1.5.2"] -> [org.bouncycastle/bcprov-jdk15on "1.50"]
[itext "4.2.1"] -> [org.bouncycastle/bcprov-jdk14 "1.38"]
[org.jfree/jfreechart] -> [com.lowagie/itext "2.1.5"] -> [bouncycastle/bcprov-jdk14 "138"]
```

I've resolved my issue by using the following exclusions, but it would be nice to get this resolved, as its a very confusing issue to encounter: adding a pdf library to your classpath breaks your login procedures.

```
[clj-pdf "2.0.9" :exclusions [org.bouncycastle/bcmail-jdk14
                                               org.bouncycastle/bcprov-jdk14
                                               org.bouncycastle/bctsp-jdk14
                                               com.lowagie/itext]]
```

**Comment by yogthos** [comment]
At some point I'd like to clean out unused stuff from itext and bouncy castle would go since clj-pdf doesn't actually need it for anything.

**Comment by yogthos** [comment]
removed bouncycastle from dependencies

**Comment by danielsz** [comment]
Just bumped into this. Could you publish the updated version to `clojars`. Thank you.

**Comment by yogthos** [comment]
ok latest `2.2.0` should be up

**Comment by danielsz** [comment]
Awesome. Thanks!
