### ISSUE TITLE
How to set font object to paragraph?

### ISSUE THREAD

**Issue by kkazuo** [yogthos/clj-pdf#61]
I could create a CJKFont object like this: (on clj-pdf:2.1.3)

    (cljpdf.text.Font. (cljpdf.text.pdf.BaseFont/createFont "HeiseiKakuGo-W5" "UniJIS-UCS2-H" cljpdf.text.pdf.BaseFont/NOT_EMBEDDED))
    ;=> #object[cljpdf.text.Font 0x4db392a2 "cljpdf.text.Font@4db392a2"]

so, how to set the font to "[:paragraph ]" or "{:font }"?

Thank you.

**Comment by yogthos** [comment]
The fonts can be set as part of metadata, e.g:
```clojure
(pdf
  [{}
  [:paragraph
   {:encoding :unicode
    :ttf-name "fonts/Arialuni.ttf"}
   "тест 123"]]
  "doc.pdf")
```

I just pushed out an update with version `2.1.4` that allows specifying a custom encoding as a string, so you should be able to do:

```clojure
[:paragraph
   {:encoding "UniJIS-UCS2-H"
    :ttf-name "HeiseiKakuGo-W5"}
   "text"]
```

Let me know if that works for you.

**Comment by kkazuo** [comment]
Wow, great! version 2.1.4 works!

Also ":font" style works good too.

    (pdf [{:font {:encoding "UniJIS-UCS2-H"
                  :ttf-name "HeiseiKakuGo-W5"}}         
          [:paragraph "Hello, world! こんにちは世界！"]]
         "doc.pdf")

Thanks a lot!

**Comment by yogthos** [comment]
Glad to hear it!
