### ISSUE TITLE
PDF-CELL {:align :center} doesn't seem to work

### ISSUE THREAD

**Issue by JMacLulich** [yogthos/clj-pdf#63]
Hi,

Firstly, thanks for the great library.

The problem I'm having is that when I use the {:align :center} keywords in the a pdf-cell the text is not being aligned. 

For example:

```clojure
oldschool-table-underlined  {:cell-border false
                                     :border-color [190 190 190]}

suffering-from
        [:pdf-table oldschool-table-underlined
         [100]
         [[:pdf-cell {:align :center :border-width-bottom 1} "Gingivitis"]]
```
I was hoping the text `Gingivitis` would be aligned in the cell in the center, but it's left justified.

Am I just specifying this incorrectly?

Thanks, Jason.

**Comment by JMacLulich** [comment]
It seems that none of the align functionality works, right alignment also doesn't work for `pdf-cell`.

I switched some of my tables to plain `table` but I have a few tables that need a image inside the cell, and I can't use a plain table.

Thanks.

**Comment by JMacLulich** [comment]
I've solved this temporarily by doing this:

```clojure
[pdf-cell [:paragraph {:align :right} "Testing"]]
```

and that right aligns the text.

**Comment by yogthos** [comment]
Yeah, so it looks like it's only possible to align horizontally if the child element is a paragraph. I wrapped strings using a `chunk`, and I switched to using a `paragraph` in [this commit](https://github.com/yogthos/clj-pdf/commit/e30f3d60c7ff5fac96f502fb9e08ba8bcbc17d8f). Should behave properly by default in the new version.

**Comment by JMacLulich** [comment]
Thanks for that, that makes sense.

I'll keep using my hack till you release the patch in an official jar on clojars.

Not sure where the best place is to ask this, but I was wondering how I can control the space between consecutive tables. It looks like there is a full line space between consecutive tables elements. I can provide more information in a separate email if you like.

**Comment by yogthos** [comment]
I pushed to Clojars already, so you should be good to go with `2.1.6`.

**Comment by yogthos** [comment]
The spacing between tables might be trickier to control, but I can take a look if you give an example. :)
