### ISSUE TITLE
Double-spacing in paragraph?

### ISSUE THREAD

**Issue by coyotespike** [yogthos/clj-pdf#64]
Thanks for making clj-pdf! 

I'm building an extensive form. I can see how to use spacing in tables, and `:spacer`, but how do I implement double-spacing instead of single-spacing within paragraphs or chunks? 

Adding `{:spacing 2}` to a `paragraph` or to `font` doesn't do the trick, for instance. (maybe this is a feature request?)

**Comment by yogthos** [comment]
This looks like it might be a new feature, it should be simple enough to do though. It looks like you'd just take the input text and replace `\n` with the number of new lines the `:spacing` key would specify. Does that sounds about right?

**Comment by coyotespike** [comment]
Hmmm - because I'm inserting information such as personal names into the template, and the names/locations vary in length, the line breaks will vary in location. 

For instance, I might have something like this:
```
[:paragraph (str
"An information charging the Petitioner with the commission of a " (:charge data) 
" arising out of the arrest was filed in " (:informationcourt data) 
". The case was dismissed.  (Exhibit A attached hereto)  The statute of limitations has expired.")]
```
Here `(:charge data)` can vary in length, and so the location where I should insert an extra line break to make it all double-spaced will vary. So, I can insert line breaks where necessary for each generated document, but I'm not sure how to do it programmatically.

Hope that makes sense!

**Comment by yogthos** [comment]
ah ok so I've got good news, I've updated the `:leading` key for paragraphs and phrases, so this should work now:

```
[:paragraph
   {:leading 25}
   "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."]]
```

The line spacing is measured in 72 units per inch, with the default spacing of 1.5 times the font height.

**Comment by coyotespike** [comment]
That totally works! Thanks so much! Although I admit I don't really understand how the magic/math works. 
:+1: :-)

**Comment by yogthos** [comment]
Actually, that part I don't know too well either. I originally based my lib on the itext library, but they changed licensing in version 5, and decided to try and scrub version 4 from the internet since it was under gpl 2. I ended up pulling the original source in and owning it now. :)

**Comment by coyotespike** [comment]
Oh yeah, I remember them changing it. I had `[clj-pdf "2.0.8" :exclusions [com.itextpdf/itextpdf]]` in my `project.clj` until just now, I think because of that. Well, way to own it ;-)

**Comment by yogthos** [comment]
Yeah, I was not impressed by that at all. They retroactively changed the published artifact in the maven central to break version 4. So, I figured I might as well take over the original code. Glad it's coming in handy. :)
