### ISSUE TITLE
Document outline

### ISSUE THREAD

**Issue by robjens** [yogthos/clj-pdf#65]
Hi Yogthos,

For the purpose of sharing user-experience and perhaps some food for thought, I figured I'd create a ticket for this.

I'm under the impression the library is mostly geared towards either full blown prose (chapters, sections, headings) or charting. Or at least that's the impression I got from reading the README and taking a look at the components + experimenting a little bit. Maybe it helps if I share that I've been trying to make a invoice but found it not at all obvious which components to use for certain things (or couldn't get them to work although they should be simple enough).

Maybe it is just that I don't understand some part about PDF components that I am sure of forms the basis for the Clojure wrapping (except that we tend to make it a lot easier on folks) so it could be just that I don't know how to use these things to make what I need... 

Obviously an invoice has tables (or at least, an order and some order rows usually) so that part is covered extensively I guess. The one thing that does instantly hit a killing blow is trying to get a (paragraph?) to align to the right at the top (head) as is custom with many forms of invoices/letters.

Also a few things are puzzling me a bit (documentation, clarity):
- what are chunks? I don't see them, or some of the other, explained in the API part of the README
- what would be the use case for some of these? (e.g. paragraph opposed to a chunk)

In my specific case, I'd be interested to learn what/if there is a equivalent to say, the CSS `<div />` element? For now, I'd recon using a `[:paragraph [:paragraph ...] [...n]]` construct for a 'multiline section of text' to align right in the head of the document but is it the right one? `section` would be something that strikes me as a candidate but I read they need to be under chapters etc.

Also it is not really clear if the optional metadata for the components is the _only_ meta data it takes? I assume not, and that generic kinds e.g. font is available on all of them. Perhaps a little clarification here and there might be something of interest. Or if not, at least I would be interested to learn.

(trying to make https://docs.google.com/document/d/1LXdovN8n_z4xkPsFRbDCDSeR0okD6Mwa9PJvmmCbu3I/edit - should be real easy right?)

It has me puzzled why align right on a paragraph won't align right. Also, is there a 100% equivalent, and is it even possible to set e.g. a paragraph to full page width?

Regards,

Rob

**Comment by yogthos** [comment]
Hi Rob,

Some of the artifacts in clj-pdf are byproducts of it being based on the iText library originally. The chunk is the smallest text segment, so it would be equivalent of a span in HTML. You'd use it inside a paragraph or a phrase to add style to a part of it. For example, if you wanted to change font or color for a piece of text in a paragraph. The paragraph would be similar to a div as you inferred.

The optional metadata is simply the metadata that can be omitted, most components don't require any metadata to be created and should have reasonable defaults.

Paragraphs go to full width, I'm not sure what you mean by them not aligning right though. The page margins are controlled by the global document metadata.

I'm using the library for reports myself and the kind of report you linked would looks as follows:

```clojure
(defn bold [text]
  [:paragraph {:style :bold} text])

(defn right-aligned [text]
  [:paragraph {:align :right} text])

(pdf/pdf
 [{}
  (right-aligned "Hotel Apartment Amsterdam")
  (right-aligned "Monument Jordaan / Brouwersgracht")
  (right-aligned 
   [:anchor {:target "www.deverdieping25.com"}
    "www.deverdieping25.com"])

  (bold "Cyril Obrecht")
  (bold "1 rue de la chapelle")
  (bold "Neuve- église, 67220")
  (bold "France")
  [:spacer 2]
  "invoice date: xx-xx-xxxx"
  "invoice nr: 2016099"
  "method: payed in cash upon arrival"
  [:table
   ["Check-in" "13-02-2016"]
   ["Check-out" "15-02-2016"]
   ["Number of persons" "4"]
   ["Arrival" "Saturday, February 13, 2016"]
   ["Departure" "Monday, February 15, 2016"]
   ["Number of nights" "2"]]
  [:table
   ["Total cost confirmed with guest"
    [:table
     {:border false}
     [[:cell {:set-border [:bottom :right]} "Room price"]
      [:cell {:set-border [:bottom]} "€ 441.44"]]
     [[:cell {:set-border [:bottom :right]} "5 % City tax"]
      [:cell {:set-border [:bottom]} "€ 22.07"]]
     [[:cell {:set-border [:bottom :right]} "6 % VAT"]
      [:cell {:set-border [:bottom]} "€ 26.49"]]
     [[:cell {:set-border [:right]}
       (bold "Total confirmed to guest")]
      (bold "€ 490")]]]]]
 "out.pdf")
```

**Comment by robjens** [comment]
Yogthos, ever so grateful - a full working example no less! I tried again and removed a stylesheet reference which seems to have been in the way because now it does work - wonder why I didn't catch that earlier, must have been the time of day. I'll close this since the question is answered / issue is resolved.

**Comment by yogthos** [comment]
:+1:
