### ISSUE TITLE
Looking for a (for ...) construct example 

### ISSUE THREAD

**Issue by iku000888** [yogthos/clj-pdf#74]
First, thank you for this awesome library.

Given a vector of image files and I want to insert the images into the pdf,
is there an idiomatic way to achieve this?

I tried a construct like:
` (pdf
   [{}
    (for [img imgvec]
      [:image img])]
   "doc.pdf"
   )
`
But it does not work because for returns 

`([:image img1] [:image img2] ...)`

while I think I need to make it return
`[:image img1] [:image img2] ...`

I would appreciate any insights and sorry that there is a high chance it is a clojure newbie question!

**Comment by yogthos** [comment]
The simplest way would probably be to just wrap them with a `:paragraph` tag, e.g:

```clojure
(pdf [{} (into [:paragraph]
              (for [img imgvec] [:image img]))] "doc.pdf" )
```

**Comment by pcwerk** [comment]
I have a similar question but this is related to table construction.  Given this function `tri-event` which takes a list of maps, and extract values for keys `:Date` `:Name` and `:Hours` and construct a vector of `:cell`s.

```
(defn tri-event
  [event]
  [[:cell {:align :left} (str (:Date event))]
   [:cell {:align :left} (str (:Name event))]
   [:cell {:align :right} (str (:Hours event))]])
```

When I try to `(map tri-event events)` inside the `table` it barfs saying that the number of columns do not match `[1 4 1]`.

```
    [:table :widths [1 4 1]}
     [[:cell {:style :bold} "Date"]
      [:cell {:style :bold} "Job/Event"]
      [:cell {:style :bold :align :right} "Hours"]]
     ;; ["2/2/2016" "foobar" "1.3"]
     (map tri-event events)
     [{}
      [:cell {:align :right} "Total  "]
      [:cell {:align :right} (str (calculate-total-hours events))]]
     ]
```

Is it not possible to do a `map` function in `table`?  If not then is there a way to build a table dynamically from a list or collection?  An example would be greatly appreciated.

Thanks!

**Comment by pcwerk** [comment]
I should note that when I do a `(first (map tri-event events))` it does in fact extract the first item in the collection (as expected).

**Comment by pcwerk** [comment]
I should also note that I've tried this below and still does not work.

```
    [:table {:border false
             :cell-border false
             :padding 0
             :spacing 0
             :widths [1 4 1]}

     [[:cell {:style :bold} "Date"]
      [:cell {:style :bold} "Job/Event"]
      [:cell {:style :bold :align :right} "Hours"]]

     (for [event events]
       [ [:cell {:align :left} (date-to-string (:Date event))]
         [:cell {:align :left} (str (:Event event))]
         [:cell {:align :right} (str (:Hours event))] ]
       )
    ]
```

**Comment by yogthos** [comment]
The header should be placed in the options map in the table as seen in the [examples here](https://github.com/yogthos/clj-pdf#table). I think what you want to do is:

```clojure
(into
  [:table {:border false
           :cell-border false
           :padding 0
           :spacing 0
           :widths [1 4 1]
           :header
           [:cell {:style :bold} "Date"]
           [:cell {:style :bold} "Job/Event"]
           [:cell {:style :bold :align :right} "Hours"]}]
  (for [event events]
    [ [:cell {:align :left} (date-to-string (:Date event))]
     [:cell {:align :left} (str (:Event event))]
     [:cell {:align :right} (str (:Hours event))]]))
```

**Comment by pcwerk** [comment]
Thanks for the quick reply.  Your suggestion is not quite correct.  As this error is now produced:

```bash
Exception in thread "main" java.lang.UnsupportedOperationException: nth not 
supported on this type: Keyword, compiling:
(/private/var/folders/mn/3tzvdmv51dddqft_v0kk_8hc0000gn/T/form-init1569613456398512543.clj:1:125)
```

This works however:

```clojure
    (into
     [:table {:widths [1 4 1]
              :padding 0
              :spacing 0
              :border false
              :font {:size 10 :family :times-roman}
              :cell-border false}
      [[:cell {:style :bold} "Date"]
       [:cell {:style :bold} "Job/Event"]
       [:cell {:style :bold :align :right} "Hours"]]]
     (for [event events]
       [[:cell {:align :left} (date-to-string (:Date event))]
        [:cell {:align :left} (str (:Event event))]
        [:cell {:align :right} (str (:Hours event))]]))
```

Note that the way loop is constructed does not work if we need to add a last row (e.g. total).  Is there a solution other than to kludge with by modifying `events` by `concat` a map `{:Event "TOTAL" :Hours (calc-total events)}`?

This is in particular challenging if you want to make total `:bold`.

**Comment by yogthos** [comment]
Yeah if you wanted to add a special row, then you'd have to do into around the `for` as well. I don't think it's really a kludge, you have to construct the correct data structure for the PDF to be generated.

One thing to look at might be the [templating](https://github.com/yogthos/clj-pdf#templating) support. You could create a template that will map the data and format it for you.

**Comment by pcwerk** [comment]
@yogthos thanks for the good feedback and excellent work with `clj-pdf`.  Appreciate it verymuch.

**Comment by yogthos** [comment]
Thanks and glad you like the library. :)

**Comment by yogthos** [comment]
and I guess we can close this one?

**Comment by iku000888** [comment]
Sorry for replying so late!
Yes I got my answer so please close it.
Thank you so much for your support!

**Comment by yogthos** [comment]
👍
