### ISSUE TITLE
Paragraph baseline skip - Is is possible to set this?

### ISSUE THREAD

**Issue by PaulSchulz** [yogthos/clj-pdf#78]
Greetings,

I would like to reduce the default baseline skip between paragraphs. I can't see anything to do this in the documentation, is it possible. (Also.. changing baseline skip within a paragraph would also be great.)

**Comment by yogthos** [comment]
I think the `:leading` key in the [paragraph tag](https://github.com/yogthos/clj-pdf#paragraph) might be what you want. There isn't any support for changing baseline skip within the paragraph itself though.

**Comment by PaulSchulz** [comment]
Thank you! This is what I need (Different terminology, but I needed to read closer)

Putting :leader into a table metadata sets the parameter for internal paragraphs, which is also good. :-)
