### ISSUE TITLE
Is it possible to insert a pdf as an image in some way?

### ISSUE THREAD

**Issue by endrebak** [yogthos/clj-pdf#92]
I want to insert pdfs in my pdf. Is this possible with clj-pdf? 

Trying the naive way with `[:image pdf]` I got

```java
IOException file:/Users/labsenter/havpryd/code/ucsc-fetch2/data/chr1_16514270_16514470.pdf
 is not a recognized imageformat.  cljpdf.text.Image.getInstance (Image.java:305)
```

Perhaps `[:graphics ...]` can handle it?

If not, suggestions for ways to convert a pdf into an image format using clojure/java, with as few dependencies as possible would be appreciated. Perhaps this would be something to insert into a faq?

**Comment by yogthos** [comment]
Currently, the only way to combine PDFs is to use the `collate` function. An image has to be something that extends java.awt.Image, so you'd have to convert the PDF you wish to insert to one externally somehow.
