### ISSUE TITLE
If I insert a large picture will the picture be shrunk or the pdf-page expanded?

### ISSUE THREAD

**Issue by endrebak** [yogthos/clj-pdf#93]
I want to insert a large (long vertically) image in my pdf and instead of having the picture shrunk I want the length of the pdf page expanded.

Is it possible to have the picture inserted as is and have the size of the pdf page expanded so the image does not have to be shrunk? I have not tried it yet, but this will be the first thing I will try on monday morning and I anticipate pain.

**Comment by yogthos** [comment]
The library will attempt to scale the picture to fit.

**Comment by endrebak** [comment]
Thanks. Do you know if there is a way to increase the page length?

**Comment by yogthos** [comment]
You can set different page sizes such as A4, legal, and so on.

**Comment by endrebak** [comment]
Or a custom size can be specified. This is great, thanks!
