### ISSUE TITLE
how to set total report background color

### ISSUE THREAD

**Issue by inturi99** [yogthos/clj-pdf#98]

**Comment by yogthos** [comment]
That's not currently supported. I'll have to see if it's possible to set a default background for pages.

**Comment by yogthos** [comment]
One workaround at the moment would be to use a watermark that's the size of the page.

**Comment by yugensoft** [comment]
Hi, I've made a PR to implement this functionality.

It is my first clojure PR. Feel free to liberally and stringently criticize the code during the review, suggest any better ways of doing the things etc. Cheers

**Comment by yogthos** [comment]
Just pushed out a new version with the fix. Thanks @yugensoft
